app <- ShinyDriver$new("../../")

Sys.sleep(2)

app$snapshotInit("ais-test1")

app$setInputs(`type-vessel_type` = "Tanker")
app$setInputs(`vessel-vessel_selected` = "Fure Fladen")
app$setInputs(`vessel-vessel_selected` = "Baltico")
app$setInputs(`vessel-vessel_selected` = "Suula")
app$setInputs(`vessel-vessel_selected` = "Leeni")
app$setInputs(`vessel-vessel_selected` = "Sealing")
app$setInputs(search_button = "click")
app$setInputs(`vessel-vessel_selected` = "Suula")
app$setInputs(search_button = "click")
app$setInputs(search_button = "click")
app$setInputs(search_button = "click")
app$setInputs(search_button = "click")
app$setInputs(search_button = "click")
app$setInputs(search_button = "click")
app$setInputs(`type-vessel_type` = "Fishing")
app$setInputs(`type-vessel_type` = "Navigation")
app$setInputs(`vessel-vessel_selected` = "By Gd")
app$setInputs(`vessel-vessel_selected` = "By Hel")
app$setInputs(search_button = "click")
app$setInputs(search_button = "click")
app$setInputs(search_button = "click")
app$setInputs(`type-vessel_type` = "High Special")
app$setInputs(`vessel-vessel_selected` = "Rivo")
app$setInputs(search_button = "click")
app$setInputs(`type-vessel_type` = "Tanker")
app$snapshot()
app$snapshot()
app$setInputs(`vessel-vessel_selected` = "Besiktas Iceland")
